Solution with 8 bags))
js-tasks-ru/js-20220311_mushkov-es pull request #4
Opened 2022-03-25 20:43 UTC by Ash1904

2022-03-29 13:52 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    constructor(data) {
а где значения по умолчанию?

2022-03-29 13:53 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        for (const value of this.data) {
лучше отдавать предпочтение методу `map` чем конкатенации строк.
Подробнее обсудим на занятии

2022-03-29 13:53 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +            const totalSales = this.data.reduce((accum, currentValue) => {
лучше отдавать предпочтение методу `map`

2022-03-29 13:53 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +            this.element.innerHTML = `<div id="orders" class="dashboard__chart_orders">
попробуйте избавиться от ветки `else` она тут явно лишняя

2022-03-29 13:54 UTC, dosandk requested changes
решение `ColumnChart` следует поправить - избавиться от лишней ветки `else` в тимплейте

2022-04-01 09:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-01 11:49 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
>  export default class ColumnChart {
good 👍

2022-04-01 11:49 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static activeNode;
good 👍 лайк за использование статического свойства

2022-04-01 11:50 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        this.remove()// Разница между удалением this и this.element
здесь мы удаляем отображение компонента из DOM

2022-04-01 11:50 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +      NotificationMessage.activeNode = this
good 👍

2022-04-01 11:50 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +      this.element = null;
а вот тут мы удаляем DOM элемент, который уже не находится в документе

2022-04-01 11:50 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    return `<div data-element="header" class="sortable-table__header sortable-table__row">
👍 good

2022-04-01 11:51 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    return cells.map(({id, template}) => {
👍 good

2022-04-01 11:51 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    console.log()
не оставляйте пустых консолей

2022-04-01 11:52 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +  flag = true;
что такое `flag`?
может лучше дать более точное имя которое подскажет зачем этот флаг нужен

2022-04-01 11:53 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +  onClick = (event) => {
👍 good  лайк за использование стрелочной функции.
совет: все стрелочные функции лучше расположить над `constructor` это улучшит читабельность компонента

2022-04-01 11:54 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    if (event.target.tagName === 'SPAN') {
а вот так лучше не делать, завтра `span` изменится на `div` и логика сломается

2022-04-01 11:55 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      let sortedData = this.sortData(this.headersConfig.find(item => item.title === name).id, this.sorted.order)
эту строку лучше разбить на несколько операций:
```
const { id } = this.headersConfig.find(item => item.title === name);

this.sortData(id, this.sorted.order);
```

2022-04-01 11:55 UTC, dosandk approved these changes
good 👍

2022-04-01 11:56 UTC, merged